In [2]:
import os

os.getcwd()

'C:\\desk\\ecommerce_churn'

In [3]:
import pandas as pd

df=pd.read_excel("online_retail_II.xlsx")

In [4]:
import os
os.listdir()

['.ipynb_checkpoints',
 'App',
 'cleaned_online_retail.csv',
 'Data',
 'data_cleaning.ipynb',
 'EDA.ipynb',
 'final_product_dashboard_dataset.csv',
 'ml_product_churn.ipynb',
 'Models',
 'Notebooks',
 'online_retail_II.xlsx',
 'product_level_dataset.csv',
 'README.md',
 'requirements.txt']

In [5]:
df.columns = df.columns.str.strip()

In [6]:
df.shape

(525461, 8)

In [7]:
file="online_retail_II.xlsx"
pd.ExcelFile(file).sheet_names

['Year 2009-2010', 'Year 2010-2011']

In [8]:
df.shape

(525461, 8)

In [9]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [11]:
df['Customer ID']=df['Customer ID'].astype('Int64')

In [13]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  Int64
 7   Country      525461 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 32.6+ MB

In [15]:
df['Invoice'].astype(str).str.startswith('C').sum()

np.int64(10206)

In [16]:
df=df[~df['Invoice'].astype(str).str.startswith('C')]

In [17]:
(df['Quantity']<0).sum()

np.int64(2121)

In [16]:
df=df[df['Quantity']>0]

In [17]:
df.shape

(1044420, 8)

In [18]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

In [19]:
(df['Price']<0).sum()

np.int64(5)

In [20]:
df=df[df['Price']>0]

In [21]:
df.isnull().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    236121
Country             0
dtype: int64

In [22]:
df=df.dropna(subset=['Description'])

In [23]:
df.duplicated().sum()

np.int64(33757)

In [18]:
df=df.drop_duplicates()

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 508414 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      508414 non-null  object
 1   StockCode    508414 non-null  object
 2   Description  505486 non-null  object
 3   Quantity     508414 non-null  int64
 4   InvoiceDate  508414 non-null  datetime64[ns]
 5   Price        508414 non-null  float64
 6   Customer ID  400947 non-null  Int64
 7   Country      508414 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 35.4+ MB

In [20]:
df['Description']=df['Description'].str.strip().str.lower()

In [21]:
df['Country']=df['Country'].str.strip().str.lower()

In [22]:
df['StockCode']=df['StockCode'].str.strip()

In [23]:
df.isnull().sum()

Invoice             0
StockCode      431266
Description      2931
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107467
Country             0
dtype: int64

In [24]:
df['TotalAmount'] = df['Quantity'] * df['Price']

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 508414 entries, 0 to 525460
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      508414 non-null  object
 1   StockCode    77148 non-null   object
 2   Description  505483 non-null  object
 3   Quantity     508414 non-null  int64
 4   InvoiceDate  508414 non-null  datetime64[ns]
 5   Price        508414 non-null  float64
 6   Customer ID  400947 non-null  Int64
 7   Country      508414 non-null  object
 8   TotalAmount  508414 non-null  float64
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 39.3+ MB

In [26]:
df['InvoiceDate'].min()

Timestamp('2009-12-01 07:45:00')

In [27]:
df['InvoiceDate'].max()

Timestamp('2010-12-09 20:01:00')

In [29]:
df.to_excel("cleaned_online_retail.xlsx", index=False)